[build]
  publish = "."

[[redirects]]
  from = "/gallery"
  to = "https://www.instagram.com/accents_and_alder_design/"
  status = 301
  force = true

[[redirects]]
  from = "/gallery.html"
  to = "https://www.instagram.com/accents_and_alder_design/"
  status = 301
  force = true
